variables:
  buildConfiguration: Release
  buildTag: $[ startsWith(variables['Build.SourceBranch'], 'refs/tags') ]
  buildNumber: $[ variables['Build.BuildNumber'] ]

trigger:
  tags:
    include:
    - '*'
  branches:
    include:
    - '*'

jobs:
- job: Linux
  pool:
    vmImage: 'ubuntu-16.04'
  steps:
  - template: azure/build.yml

- job: Windows_build
  pool:
    vmImage: 'vs2017-win2016'
  condition: ne(variables['Build.SourceBranch'], 'refs/heads/dev')
  steps:
  - template: azure/build.yml

- job: Windows_deploy
  pool:
    vmImage: 'vs2017-win2016'
  condition: |
      and (
        succeeded(),
        eq(variables['Build.SourceBranch'], 'refs/heads/dev')
      )
  steps:
  - template: azure/build.yml
  - template: azure/deploy.yml
